"use strict";
const username = "Ezhavarasan";
let age = 24;
const email = "ezhavarasan2003b@gmail.com";
const issubscribed = true;
let city = "Banglore";
let count = 5;
age = age + 1;
const userProfileMessage = `Hello ${username}, you are ${age} years old and your email is ${email}.`;
const isEligibleForPremium = (age > 18) && issubscribed;
const isAdult = age >= 18;
const hasHighLogin = count > 3;
console.log("User Name:", username);
console.log("Age after increment:", age);
console.log("Email:", email);
console.log("Subscribed:", issubscribed);
console.log("City (Type Inference):", city);
console.log("Login Count (Type Inference):", count);
console.log("User Profile Message:", userProfileMessage);
console.log("Is Adult:", isAdult);
console.log("Has High Login Count:", hasHighLogin);
console.log("Eligible for Premium Plan:", isEligibleForPremium);
